#!/bin/bash
# A script to onboard OpenShift cluster to CloudGuard
# Author: Jayden Kyaw Htet Aung (Regional Cloud & DevSecOps Architect, Check Point)

# Name of your cluster that will appear on CloudGuard portal. Update this value.
cluster_name="mycluster"

# namespace for CloudGuard (default is checkpoint) 
namespace="checkpoint"

# Your CloudGuard API Key and Secret
CHKP_CLOUDGUARD_API="your-cloudguard-api"
CHKP_CLOUDGUARD_SECRET="your-cloudguard-secret"

dome9ApiUrl="https://api.dome9.com"

# Your Cluster ID which is generated by CloudGuard. 
CREATION_RESPONSE=$(curl -s -X POST $dome9ApiUrl/v2/KubernetesAccount --header 'Content-Type: application/json' --header 'Accept: application/json' \
-d "{\"name\" : \"$cluster_name\"}" --user $CHKP_CLOUDGUARD_API:$CHKP_CLOUDGUARD_SECRET)

export cluster_id=$(echo $CREATION_RESPONSE | jq -r '.id')

# Create your name space
oc create namespace $myns

# Generate secret
oc create secret generic dome9-creds \
--from-literal=username=$CHKP_CLOUDGUARD_API \
--from-literal=secret=$CHKP_CLOUDGUARD_SECRET \
--namespace $myns

# Create Configmap

oc create configmap cp-resource-management-configmap \
--from-literal=cluster.id=,$cluster_id --namespace $myns

# Create Services account
oc create serviceaccount cp-resource-management --namespace $myns

echo Service Account "${myns}" has been created. 

#Create Admin User. Make sure uid1000.json is in the same directory.
oc create -f uid1000.json --as system:admin

# Policy Add User
oc adm policy add-scc-to-user uid1000 -z cp-resource-management --as system:admin

# Create Cluster role
oc create clusterrole cp-resource-management \
--verb=get,list \
--resource=pods,nodes,services,nodes/proxy,networkpolicies.networking.k8s.io,ingresses.extensions,podsecuritypolicies,roles,rolebindings,clusterroles,clusterrolebindings,serviceaccounts,namespaces

# Clusterrole binding
oc create clusterrolebinding cp-resource-management \
--clusterrole=cp-resource-management \
--serviceaccount=prod:cp-resource-management

# Deploy CloudGuard 
oc create -f cp-cloudguard-openshift.yaml --namespace=$myns

echo Cluster onboarding has been finished. 


